version: '2'
services:
    php:
        build: .
        ports:
            - '8000:80'
        volumes:
            - ~/.composer-docker/cache:/root/.composer/cache:delegated
            - ./:/app:delegated
        networks:
            - prova
    phpmyadmin:
        image: 'phpmyadmin:latest'
        ports:
            - 8080:80
        networks:
            - prova
        environment:
            - PMA_ARBITRARY=1
    mysql:
        image: 'mysql/mysql-server:8.0'
        networks:
            - prova
        ports:
            - '3306:3306'
        environment:
            MYSQL_ROOT_PASSWORD: 'password'
            MYSQL_ROOT_HOST: '%'
            MYSQL_DATABASE: 'yii-prova-api'
            MYSQL_USER: 'user'
            MYSQL_PASSWORD: 'password'
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
networks:
    prova:
        driver: bridge
